; Test.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 61.0
.source Test.java
.class public Test
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 3
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 2
  .limit locals 2
  .line 6
  0: ldc "4"
  2: ldc "4"
  4: invokevirtual java/lang/String/concat(Ljava/lang/String;)Ljava/lang/String;
  7: astore_1
  .line 8
  8: aload_1
  9: invokestatic io/writeString(Ljava/lang/String;)V
  .line 10
  12: return
.end method

